# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 1

before:
  hooks:
    - go mod tidy

builds:
  - binary: gsa
    main: ./cmd/gsa
    ldflags:
        - "-s -w"
        - -X github.com/Zxilly/go-size-analyzer.version={{.Version}}
        - -X github.com/Zxilly/go-size-analyzer.buildDate={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    flags: -trimpath
    tags:
      - embed

archives:
  - format: tar.gz
    name_template: >-
      {{- .ProjectName }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"