package tui

import (
	"strings"
	"testing"

	"github.com/charmbracelet/x/ansi"
)

func TestDetailSetMarkdownResetsScrollOnContentChange(t *testing.T) {
	d := newDetailModel()
	d.SetWidth(40)
	d.SetHeight(5)
	d.SetMarkdown(strings.Repeat("- old item\n", 40))
	d.viewPort.ScrollDown(10)
	if got := d.viewPort.YOffset(); got == 0 {
		t.Fatal("expected detail viewport to scroll before changing content")
	}

	d.SetMarkdown(strings.Repeat("- new item\n", 40))

	if got := d.viewPort.YOffset(); got != 0 {
		t.Fatalf("detail viewport YOffset after content change=%d want 0", got)
	}
}

func TestDetailMarkdownStyleDoesNotAddBlankLineAfterHeading(t *testing.T) {
	d := newDetailModel()
	d.SetWidth(80)
	d.SetHeight(10)
	d.SetMarkdown("## Files\n### C:/src/pkg\n- a.go\n")

	got := ansi.Strip(d.viewPort.View())

	if strings.Contains(got, "Files\n\n") {
		t.Fatalf("rendered markdown has blank line after Files heading:\n%s", got)
	}
	if strings.Contains(got, "C:/src/pkg\n\n") {
		t.Fatalf("rendered markdown has blank line after directory heading:\n%s", got)
	}
}

func TestDetailMarkdownRendersEscapedAutogeneratedFileName(t *testing.T) {
	d := newDetailModel()
	d.SetWidth(80)
	d.SetHeight(10)
	d.SetMarkdown("## Files\n### (root)\n- &lt;autogenerated&gt;\n")

	got := ansi.Strip(d.viewPort.View())

	if !strings.Contains(got, "<autogenerated>") {
		t.Fatalf("rendered markdown missing literal autogenerated file name:\n%s", got)
	}
}
