package tui

import (
	"sync"
	"testing"

	"github.com/stretchr/testify/assert"

	"github.com/Zxilly/go-size-analyzer/internal/entity"
)

func Test_newWrapper(t *testing.T) {
	assert.Panics(t, func() {
		newWrapper(nil)
	})
}

func Test_wrapper_Description(t *testing.T) {
	w := wrapper{}
	assert.Panics(t, func() {
		w.Description()
	})
}

func Test_wrapper_DescriptionUsesPlaceholderForUnknownSourceFile(t *testing.T) {
	pkg := entity.NewPackage()
	pkg.Name = "pkg"
	pkg.Type = entity.PackageTypeVendor
	pkg.Files = append(pkg.Files,
		&entity.File{PkgName: pkg.Name},
		&entity.File{FilePath: " \t\r\n", PkgName: pkg.Name},
		&entity.File{FilePath: "C:/src/pkg/", PkgName: pkg.Name},
	)

	w := newWrapper(pkg)
	got := w.Description()

	assert.Contains(t, got, "### (unknown source)\n- (unknown source)")
	assert.Contains(t, got, "### C:/src/pkg\n- (unknown source)")
	assert.NotContains(t, got, "\n- \n")
}

func Test_wrapper_DescriptionGroupsFilesByDirectory(t *testing.T) {
	pkg := entity.NewPackage()
	pkg.Name = "pkg"
	pkg.Type = entity.PackageTypeVendor
	pkg.Files = append(pkg.Files,
		&entity.File{FilePath: "C:/src/pkg/b.go", PkgName: pkg.Name},
		&entity.File{FilePath: "C:/src/other/c.go", PkgName: pkg.Name},
		&entity.File{FilePath: "C:/src/pkg/a.go", PkgName: pkg.Name},
	)

	w := newWrapper(pkg)
	got := w.Description()

	assert.Contains(t, got, "## Files\n### C:/src/other\n- c.go")
	assert.Contains(t, got, "### C:/src/pkg\n- a.go\n- b.go")
	assert.NotContains(t, got, "C:/src/pkg/a.go")
}

func Test_wrapper_DescriptionEscapesAutogeneratedFileName(t *testing.T) {
	pkg := entity.NewPackage()
	pkg.Name = "runtime"
	pkg.Type = entity.PackageTypeStd
	pkg.Files = append(pkg.Files, &entity.File{FilePath: "<autogenerated>", PkgName: pkg.Name})

	w := newWrapper(pkg)
	got := w.Description()

	assert.Contains(t, got, "### (root)\n- &lt;autogenerated&gt;")
	assert.NotContains(t, got, "- <autogenerated>")
}

func Test_wrapper_DescriptionTrimsLeadingSlashFromSubPackages(t *testing.T) {
	pkg := entity.NewPackage()
	pkg.Name = "runtime"
	pkg.Type = entity.PackageTypeStd
	pkg.SubPackages["/consts"] = entity.NewPackage()
	pkg.SubPackages["\\debug"] = entity.NewPackage()

	w := newWrapper(pkg)
	got := w.Description()

	assert.Contains(t, got, "- consts")
	assert.Contains(t, got, "- debug")
	assert.NotContains(t, got, "- /consts")
	assert.NotContains(t, got, "- \\debug")
}

func Test_wrapper_Title(t *testing.T) {
	w := wrapper{}
	assert.Panics(t, func() {
		w.Title()
	})

	w = wrapper{function: &entity.Function{
		Type: "invalid",
	}}

	assert.Panics(t, func() {
		w.Title()
	})
}

func Test_wrapper_FileTitleUsesPlaceholderForUnknownSourceFile(t *testing.T) {
	w := newWrapper(&entity.File{})

	assert.Equal(t, "(unknown source)", w.Title())
	assert.Contains(t, w.Description(), "# (unknown source) _(File)_")
	assert.Contains(t, w.Description(), "- **Path:** (unknown source)")
}

func Test_wrapper_MethodDescriptionTitleIncludesReceiver(t *testing.T) {
	w := newWrapper(&entity.Function{
		Name:     "ServeHTTP",
		Type:     entity.FuncTypeMethod,
		Receiver: "Handler",
	})

	assert.Contains(t, w.Description(), "# Handler.ServeHTTP _(Function)_")
}

func Test_wrapper_children(t *testing.T) {
	w := wrapper{cacheOnce: &sync.Once{}}
	assert.Panics(t, func() {
		w.children()
	})
}

func Test_wrapper_size(t *testing.T) {
	w := wrapper{}
	assert.Panics(t, func() {
		w.size()
	})
}
